### ISSUE TITLE
How does app mesh handle sig v4?

### ISSUE THREAD

**Issue by chenrui333** [aws/aws-app-mesh-examples#187]
Curious about how does app mesh integrate with sig v4 check.

Thanks!

**Comment by lavignes** [comment]
Hey @chenrui333 I'm assuming you are asking about how our Envoy proxy integrates with AWS IAM using sig v4.

Right now, the [envoy image](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) we distribute for use with App Mesh, is a fork of of Envoy with a custom extension that sig v4-signs requests made via Envoy's [xDS protocol](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol). Since xDS uses a GRPC protocol (which is in turn HTTP/2) we can trivially apply the [sig v4 algorithm](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) on it.

We are looking to upstream this extension to the official project so customers can ultimately just use an unaltered Envoy build (or their own custom build) on App Mesh. In fact, the integration is almost complete. I have a final pull request open that will enable the extension: envoyproxy/envoy/pull/7532

**Comment by lavignes** [comment]
@chenrui333 I'm going to assume this answers your question for now. Feel free to re-open if I misinterpreted the question or need more clarification.
