### ISSUE TITLE
Self-hosted Kubernetes cluster logging

### ISSUE THREAD

**Issue by daparthi001** [aws/aws-app-mesh-examples#87]
**Describe the bug**
Unable to configure the logs to cloudwatch

**Platform**
ec2 running kubernetes

Unable to send logs from the pods to cloudwatch as ECS ,any help on it ?

**Comment by bcelenza** [comment]
Hey @daparthi001 , a few questions:

1. Could you provide some additional information on your Kubernetes/Pod configuration? 
2. What specific logs are you trying to send from your pods?
3. Are you seeing any errors when attempting to transmit logs to CloudWatch?
4. You mention sending to CloudWatch as ECS. What do you mean by this? Is your Kubernetes setup running on ECS with EC2 launch type, or EC2 without ECS?

Also, out of curiosity, have you tried running your cluster on EKS instead of hosting your own Kubernetes setup?

**Comment by daparthi001** [comment]
We are kubernetes cluster on single node as part of my testing in sandbox environment .
I deployed the the application pods using the colorapp.yaml generated through below ,just replaced meshname and images and service domain .The yaml configuration file doesn't contain log related info as the ecs colorapp.yaml 
kubernetes 
https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/kubernetes/generate-templates.sh

ECS colorapp:
https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/ecs-colorapp.yaml

**Comment by bcelenza** [comment]
I see. Yes, this is because Kubernetes does not have the same simplified log setup as ECS -- there's no direct 1:1 relationship between the two that I'm aware of (I could be wrong).

Here are a couple guides that can help you get logging stood up on your workers:

1. Sending Kubernetes logs to CloudWatch: https://blog.csanchez.org/2018/06/26/sending-kubernetes-logs-to-cloudwatch-logs-using-fluentd/
2. Logging with EKS and Fluentd (applies even if you aren't using EKS): https://eksworkshop.com/logging/. More advanced guide that includes ElasticSearch, which is a nice add-on.

Hope this helps!
